// <auto-generated />
namespace Projeto_Cinema.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class deleteoncascadesession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteoncascadesession));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240042245_delete-on-cascade-session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
